export default {
 content: [
  "./app/**/*.{js,ts,jsx,tsx,mdx}",
  "./src/**/*.{js,ts,jsx,tsx,mdx}",
],
  corePlugins: { preflight: true },
  theme: {
    extend: {
      colors: {
        "7-primitive-primary-neutral-100":
          "var(--7-primitive-primary-neutral-100)",
        "7-primitive-primary-neutral-800":
          "var(--7-primitive-primary-neutral-800)",
        "backgroundbg-black": "var(--backgroundbg-black)",
        "backgroundbg-blue": "var(--backgroundbg-blue)",
        "backgroundbg-bluish-gray": "var(--backgroundbg-bluish-gray)",
        "backgroundbg-gray": "var(--backgroundbg-gray)",
        "backgroundbg-green": "var(--backgroundbg-green)",
        "backgroundbg-lime": "var(--backgroundbg-lime)",
        "backgroundbg-red": "var(--backgroundbg-red)",
        "backgroundbg-white": "var(--backgroundbg-white)",
        "backgroundbg-yellow": "var(--backgroundbg-yellow)",
        "foundation-blueblue-100": "var(--foundation-blueblue-100)",
        "foundation-blueblue-200": "var(--foundation-blueblue-200)",
        "foundation-blueblue-300": "var(--foundation-blueblue-300)",
        "foundation-blueblue-400": "var(--foundation-blueblue-400)",
        "foundation-blueblue-50": "var(--foundation-blueblue-50)",
        "foundation-blueblue-500": "var(--foundation-blueblue-500)",
        "foundation-blueblue-600": "var(--foundation-blueblue-600)",
        "foundation-blueblue-700": "var(--foundation-blueblue-700)",
        "foundation-blueblue-800": "var(--foundation-blueblue-800)",
        "foundation-blueblue-900": "var(--foundation-blueblue-900)",
        "foundation-graygray-300": "var(--foundation-graygray-300)",
        "foundation-graygray-50": "var(--foundation-graygray-50)",
        "foundation-graygray-500": "var(--foundation-graygray-500)",
        "foundation-graygray-600": "var(--foundation-graygray-600)",
        "foundation-graygray-700": "var(--foundation-graygray-700)",
        "foundation-graygray-800": "var(--foundation-graygray-800)",
        "foundation-graygray-900": "var(--foundation-graygray-900)",
        "foundation-greengreen-100": "var(--foundation-greengreen-100)",
        "foundation-greengreen-200": "var(--foundation-greengreen-200)",
        "foundation-greengreen-300": "var(--foundation-greengreen-300)",
        "foundation-greengreen-400": "var(--foundation-greengreen-400)",
        "foundation-greengreen-50": "var(--foundation-greengreen-50)",
        "foundation-greengreen-500": "var(--foundation-greengreen-500)",
        "foundation-greengreen-600": "var(--foundation-greengreen-600)",
        "foundation-greengreen-800": "var(--foundation-greengreen-800)",
        "foundation-greengreen-900": "var(--foundation-greengreen-900)",
        "foundation-limelime-100": "var(--foundation-limelime-100)",
        "foundation-limelime-200": "var(--foundation-limelime-200)",
        "foundation-limelime-300": "var(--foundation-limelime-300)",
        "foundation-limelime-400": "var(--foundation-limelime-400)",
        "foundation-limelime-50": "var(--foundation-limelime-50)",
        "foundation-limelime-500": "var(--foundation-limelime-500)",
        "foundation-limelime-600": "var(--foundation-limelime-600)",
        "foundation-limelime-700": "var(--foundation-limelime-700)",
        "foundation-limelime-800": "var(--foundation-limelime-800)",
        "foundation-limelime-900": "var(--foundation-limelime-900)",
        "foundation-redred-100": "var(--foundation-redred-100)",
        "foundation-redred-200": "var(--foundation-redred-200)",
        "foundation-redred-300": "var(--foundation-redred-300)",
        "foundation-redred-400": "var(--foundation-redred-400)",
        "foundation-redred-50": "var(--foundation-redred-50)",
        "foundation-redred-500": "var(--foundation-redred-500)",
        "foundation-redred-600": "var(--foundation-redred-600)",
        "foundation-redred-700": "var(--foundation-redred-700)",
        "foundation-redred-800": "var(--foundation-redred-800)",
        "foundation-redred-900": "var(--foundation-redred-900)",
        "foundation-whitewhite-100": "var(--foundation-whitewhite-100)",
        "foundation-whitewhite-200": "var(--foundation-whitewhite-200)",
        "foundation-whitewhite-300": "var(--foundation-whitewhite-300)",
        "foundation-whitewhite-400": "var(--foundation-whitewhite-400)",
        "foundation-whitewhite-50": "var(--foundation-whitewhite-50)",
        "foundation-whitewhite-500": "var(--foundation-whitewhite-500)",
        "foundation-whitewhite-600": "var(--foundation-whitewhite-600)",
        "foundation-whitewhite-700": "var(--foundation-whitewhite-700)",
        "foundation-whitewhite-800": "var(--foundation-whitewhite-800)",
        "foundation-whitewhite-900": "var(--foundation-whitewhite-900)",
        "foundation-yellowyellow-100": "var(--foundation-yellowyellow-100)",
        "foundation-yellowyellow-200": "var(--foundation-yellowyellow-200)",
        "foundation-yellowyellow-300": "var(--foundation-yellowyellow-300)",
        "foundation-yellowyellow-400": "var(--foundation-yellowyellow-400)",
        "foundation-yellowyellow-50": "var(--foundation-yellowyellow-50)",
        "foundation-yellowyellow-500": "var(--foundation-yellowyellow-500)",
        "foundation-yellowyellow-600": "var(--foundation-yellowyellow-600)",
        "foundation-yellowyellow-700": "var(--foundation-yellowyellow-700)",
        "foundation-yellowyellow-800": "var(--foundation-yellowyellow-800)",
        "foundation-yellowyellow-900": "var(--foundation-yellowyellow-900)",
        "foundationblackblack-100": "var(--foundationblackblack-100)",
        "foundationblackblack-200": "var(--foundationblackblack-200)",
        "foundationblackblack-300": "var(--foundationblackblack-300)",
        "foundationblackblack-400": "var(--foundationblackblack-400)",
        "foundationblackblack-50": "var(--foundationblackblack-50)",
        "foundationblackblack-500": "var(--foundationblackblack-500)",
        "foundationblackblack-600": "var(--foundationblackblack-600)",
        "foundationblackblack-700": "var(--foundationblackblack-700)",
        "foundationblackblack-800": "var(--foundationblackblack-800)",
        "foundationblackblack-900": "var(--foundationblackblack-900)",
        "foundationgraygray-100": "var(--foundationgraygray-100)",
        "foundationgraygray-200": "var(--foundationgraygray-200)",
        "foundationgraygray-400": "var(--foundationgraygray-400)",
        "foundationgreengreen-700": "var(--foundationgreengreen-700)",
        "mode-app-background": "var(--mode-app-background)",
        "mode-app-border": "var(--mode-app-border)",
        "mode-app-foreground": "var(--mode-app-foreground)",
        "mode-sidebar-border": "var(--mode-sidebar-border)",
        "mode-sidebar-foreground": "var(--mode-sidebar-foreground)",
        "primaryprimary-green": "var(--primaryprimary-green)",
        "strokestroke-blue": "var(--strokestroke-blue)",
        "strokestroke-gray": "var(--strokestroke-gray)",
        "strokestroke-gray-darker": "var(--strokestroke-gray-darker)",
        "strokestroke-green": "var(--strokestroke-green)",
        "strokestroke-lime": "var(--strokestroke-lime)",
        "strokestroke-red": "var(--strokestroke-red)",
        "strokestroke-yellow": "var(--strokestroke-yellow)",
        "text-colortext-black": "var(--text-colortext-black)",
        "text-colortext-blue": "var(--text-colortext-blue)",
        "text-colortext-dark": "var(--text-colortext-dark)",
        "text-colortext-gray": "var(--text-colortext-gray)",
        "text-colortext-green": "var(--text-colortext-green)",
        "text-colortext-lime": "var(--text-colortext-lime)",
        "text-colortext-red": "var(--text-colortext-red)",
        "text-colortext-white": "var(--text-colortext-white)",
        "text-colortext-yellow": "var(--text-colortext-yellow)",
        "tw-colors-gray-50": "var(--tw-colors-gray-50)",
        "tw-colors-neutral-200": "var(--tw-colors-neutral-200)",
        "tw-colors-neutral-200-duplicate":
          "var(--tw-colors-neutral-200-duplicate)",
        "tw-colors-neutral-950": "var(--tw-colors-neutral-950)",
        "tw-colors-white": "var(--tw-colors-white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        body: "var(--body-font-family)",
        "inter-2xl-bold-2xl": "var(--inter-2xl-bold-2xl-font-family)",
        "inter-2xl-medium-2xl": "var(--inter-2xl-medium-2xl-font-family)",
        "inter-2xl-regular-2xl": "var(--inter-2xl-regular-2xl-font-family)",
        "inter-2xl-semibold-2xl": "var(--inter-2xl-semibold-2xl-font-family)",
        "inter-3xl-bold-3xl": "var(--inter-3xl-bold-3xl-font-family)",
        "inter-3xl-medium-3xl": "var(--inter-3xl-medium-3xl-font-family)",
        "inter-3xl-regular-3xl": "var(--inter-3xl-regular-3xl-font-family)",
        "inter-3xl-semibold-3xl": "var(--inter-3xl-semibold-3xl-font-family)",
        "inter-4xl-bold-4xl": "var(--inter-4xl-bold-4xl-font-family)",
        "inter-4xl-medium-4xl": "var(--inter-4xl-medium-4xl-font-family)",
        "inter-4xl-regular-4xl": "var(--inter-4xl-regular-4xl-font-family)",
        "inter-4xl-semibold-4xl": "var(--inter-4xl-semibold-4xl-font-family)",
        "inter-5xl-bold-5xl": "var(--inter-5xl-bold-5xl-font-family)",
        "inter-5xl-medium-5xl": "var(--inter-5xl-medium-5xl-font-family)",
        "inter-5xl-regular-5xl": "var(--inter-5xl-regular-5xl-font-family)",
        "inter-5xl-semibold-5xl": "var(--inter-5xl-semibold-5xl-font-family)",
        "inter-base-bold-base": "var(--inter-base-bold-base-font-family)",
        "inter-base-medium-base": "var(--inter-base-medium-base-font-family)",
        "inter-base-regular-base": "var(--inter-base-regular-base-font-family)",
        "inter-base-semibold-base":
          "var(--inter-base-semibold-base-font-family)",
        "inter-lg-bold-lg": "var(--inter-lg-bold-lg-font-family)",
        "inter-lg-medium-lg": "var(--inter-lg-medium-lg-font-family)",
        "inter-lg-regular-lg": "var(--inter-lg-regular-lg-font-family)",
        "inter-lg-semibold-lg": "var(--inter-lg-semibold-lg-font-family)",
        "inter-sm-bold-sm": "var(--inter-sm-bold-sm-font-family)",
        "inter-sm-medium-sm": "var(--inter-sm-medium-sm-font-family)",
        "inter-sm-regular-sm": "var(--inter-sm-regular-sm-font-family)",
        "inter-sm-semibold-sm": "var(--inter-sm-semibold-sm-font-family)",
        "inter-xl-bold-xl": "var(--inter-xl-bold-xl-font-family)",
        "inter-xl-medium-xl": "var(--inter-xl-medium-xl-font-family)",
        "inter-xl-regular-xl": "var(--inter-xl-regular-xl-font-family)",
        "inter-xl-semibold-xl": "var(--inter-xl-semibold-xl-font-family)",
        "inter-xs-bold-xs": "var(--inter-xs-bold-xs-font-family)",
        "inter-xs-medium-xs": "var(--inter-xs-medium-xs-font-family)",
        "inter-xs-regular-xs": "var(--inter-xs-regular-xs-font-family)",
        "inter-xs-semibold-xs": "var(--inter-xs-semibold-xs-font-family)",
        mono: "var(--mono-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate")],
  darkMode: ["class"],
};